# Generated by Django 4.1.5 on 2023-01-13 00:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_card_management', '0003_alter_purchase_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='firstInstallmentDate',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
