# Generated by Django 4.1.5 on 2023-01-13 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('credit_card_management', '0004_alter_purchase_firstinstallmentdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=1, null=True)),
                ('value_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_card_management.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
